language: java

cache:
  directories:
  - "$HOME/.m2"

env:
  global:

jdk:
- openjdk8
- oraclejdk8

after_success:
- test ${TRAVIS_PULL_REQUEST:-true} = false -a ${TRAVIS_BRANCH:-HEAD} = develop &&
  test "${OSSRH_USERNAME:}" &&
  mvn -s .travis/maven-settings.xml deploy -Dquick
